### ISSUE TITLE
Tab-Sequence order of "Ocha Services"-Button

### ISSUE THREAD

**Issue by MarcusMorba** [UN-OCHA/common_design#413]
Maybe the current behaviour is the wanted behaviour?

Nevertheless - the visual order of the buttons within the site-header does not match the TAB-sequence order as the "OCHA Services"-button in the DOM is after the "Login"-button. Visually it´s the first button after the "skip link"-section.

See demo site: https://web.brand.unocha.org

**Comment by rupl** [comment]
You're right, they don't match. The OCHA Services menu is a bit like a guest who stays too long after a party has ended. We have it there for historical reasons, but are in the process of collecting data to prove that it's rarely used.

I think the quickest fix to ensure that the tab order matches visual order would be to change how we re-insert the element into the DOM: https://github.com/UN-OCHA/common_design/blob/1be9b7af953766fa86694ab750f2c1a8f794489e/js/cd-ocha-services.js#L13-L21

**Comment by MarcusMorba** [comment]
Thanks for the fast feedback.
