### ISSUE TITLE
Use feature query for better PE for Hero component

### ISSUE THREAD

**Issue by left23** [UN-OCHA/common_design#67]
https://github.com/UN-OCHA/common_design/blob/0ab0a1ddfae997cbfe6a3b5dff16f72d7018a81b/components/cd-hero/cd-hero.css#L13

Refer to IASC https://github.com/UN-OCHA/iasc8/blob/develop/html/themes/custom/iasc_common_design/sass/components/cd-hero/cd-hero.scss#L17
```
@supports (object-fit: cover) {
  .cd-hero__image {
    object-fit: cover;
    object-position: 50% 50%;
  }
}
```

**Comment by rupl** [comment]
love me some object-fit! great idea.
