### ISSUE TITLE
Event listener is not attached to button when it is recreated by cd-dropdown JS

### ISSUE THREAD

**Issue by left23** [UN-OCHA/common_design#87]
https://github.com/UN-OCHA/common_design/blob/48cb59cda351f063a12cefb8ecc834a3dc7aade1/js/cd-search--inline.js#L14

When the search is toggled on mobile, the input should be given focus (it is styled with a drop shadow). This still works on initial page load but when the viewport is resized from desktop to mobile, and the search toggler button is removed and recreated, the event listener is not attached so input is not given focus when the Button is toggled.

**Comment by orakili** [comment]
@left23 Untested, but maybe the adding the event on the parent could do the trick:

```javascript
(function (Drupal) {
  'use strict';

  Drupal.behaviors.cdSearchInline = {
    attach: function (context, settings) {
      var searchInput = context.querySelector('.cd-search--inline__input');

      function focusInput(event) {
        var searchButton = context.querySelector('.cd-search--inline__btn');
        if (searchButton && event.currentTarget === searchButton) {
          searchInput.focus();
        }
      }

      if (searchInput) {
        searchInput.parentNode.addEventListener('click', focusInput);
      }
    }
  };
})(Drupal);
```

**Comment by left23** [comment]
@orakili Would you mind putting this in a PR if you have a solution? Thanks!

**Comment by left23** [comment]
Thanks @orakili 
I'll put this into a PR soon and I think it means I can remove the cd-search.js and cd-search--inline.js files too which is great!
